apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: observability
  labels: {app: blackbox-exporter}
spec:
  selector: {app: blackbox-exporter}
  ports:
  - name: http
    port: 9115
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels: {app: blackbox-exporter}
  template:
    metadata:
      labels: {app: blackbox-exporter}
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: blackbox
        image: prom/blackbox-exporter:v0.24.0
        args: ["--config.file=/config/blackbox.yaml"]
        ports:
        - name: http
          containerPort: 9115
        volumeMounts:
        - name: config
          mountPath: /config
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities: {drop: ["ALL"]}
      volumes:
      - name: config
        configMap:
          name: blackbox-exporter-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
  namespace: observability
data:
  blackbox.yaml: |
    modules:
      tcp_connect:
        prober: tcp
      http_2xx:
        prober: http
        http:
          preferred_ip_protocol: "ip4"
