apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ops-system
resources: []
helmCharts:
- name: argo-rollouts
  repo: https://argoproj.github.io/argo-helm
  version: 2.38.3
  releaseName: argo-rollouts
  namespace: ops-system
