apiVersion: v1
kind: Endpoints
metadata:
  name: onprem-eth
  namespace: prod-infra
subsets:
- addresses:
  - ip: 10.50.10.101
  ports:
  - name: p2p
    port: 30303
  - name: rpc
    port: 8545
---
apiVersion: v1
kind: Service
metadata:
  name: onprem-eth
  namespace: prod-infra
spec:
  clusterIP: None
  ports:
  - name: p2p
    port: 30303
  - name: rpc
    port: 8545
