apiVersion: v1
kind: Service
metadata:
  name: msk-bootstrap
  namespace: prod-infra
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  clusterIP: None
  ports:
  - name: kafka
    port: 9092
  publishNotReadyAddresses: true
---
apiVersion: v1
kind: Endpoints
metadata:
  name: msk-bootstrap
  namespace: prod-infra
subsets:
- addresses:
  - ip: 10.100.30.10
  - ip: 10.100.30.11
  - ip: 10.100.30.12
  ports:
  - name: kafka
    port: 9092
