apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: listener
  namespace: prod-exchange
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: listener
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
