apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: general
  namespace: ops-system
spec:
  template:
    metadata:
      labels:
        node.kubernetes.io/lifecycle: spot
    spec:
      nodeClassRef:
        name: default
      taints: []
      startupTaints: []
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot","on-demand"]
      - key: kubernetes.io/arch
        operator: In
        values: ["amd64"]
      - key: kubernetes.io/os
        operator: In
        values: ["linux"]
      - key: node.kubernetes.io/instance-type
        operator: In
        values: ["m6i.large","m7i.flex.large","c7i.large"]
  disruption:
    consolidateAfter: 30s
  limits:
    cpu: "200"
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
  namespace: ops-system
spec:
  amiFamily: AL2
  subnetSelectorTerms:
  - tags:
      Name: "cx-portfolio-private*"
  securityGroupSelectorTerms:
  - tags:
      karpenter: "enabled"
  role: "KarpenterNodeRole-1234"
  detailedMonitoring: true
