apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources: []
helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: 62.7.0
  releaseName: kps
  namespace: observability
  valuesFile: values.yaml
