apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ops-system
resources: []
helmCharts:
- name: secrets-store-csi-driver
  repo: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
  version: 1.4.6
  releaseName: csi-secrets-store
  namespace: ops-system
- name: secrets-store-csi-driver-provider-aws
  repo: https://aws.github.io/secrets-store-csi-driver-provider-aws
  version: 0.3.9
  releaseName: csi-provider-aws
  namespace: ops-system
