apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-sm-wallet
  namespace: prod-wallet
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "wallet/key-id"
        objectType: "secretsmanager"
      - objectName: "wallet/key-pw"
        objectType: "secretsmanager"
  secretObjects:
  - secretName: wallet-credentials
    type: Opaque
    data:
    - objectName: "wallet/key-id"
      key: WALLET_KEY_ID
    - objectName: "wallet/key-pw"
      key: WALLET_KEY_PW
---
apiVersion: v1
kind: Pod
metadata:
  name: wallet-secret-sync
  namespace: prod-wallet
spec:
  serviceAccountName: signer
  volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "aws-sm-wallet"
  containers:
  - name: sync
    image: public.ecr.aws/docker/library/busybox:1.36
    command: ["sh","-c","sleep 3600"]
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
