apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: risk-svc
  namespace: prod-risk
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: risk-svc
  minReplicas: 3
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target: { type: Utilization, averageUtilization: 60 }
