apiVersion: v1
kind: ServiceAccount
metadata:
  name: risk-svc
  namespace: prod-risk
  labels:
    app.kubernetes.io/managed-by: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: risk-svc
  namespace: prod-risk
  labels:
    app.kubernetes.io/managed-by: argocd
rules:
- apiGroups: [""]
  resources: ["configmaps","pods"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: risk-svc
  namespace: prod-risk
  labels:
    app.kubernetes.io/managed-by: argocd
subjects:
- kind: ServiceAccount
  name: risk-svc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: risk-svc
