apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: order-svc
  namespace: prod-exchange
  labels: { app.kubernetes.io/managed-by: argocd }
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: order-svc }
  minReplicas: 3
  maxReplicas: 40
  metrics:
  - type: Resource
    resource: { name: cpu, target: { type: Utilization, averageUtilization: 70 } }
