apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-svc
  namespace: prod-exchange
  labels: { app.kubernetes.io/managed-by: argocd }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: order-svc
  namespace: prod-exchange
  labels: { app.kubernetes.io/managed-by: argocd }
rules:
- apiGroups: [""]
  resources: ["configmaps","pods"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: order-svc
  namespace: prod-exchange
  labels: { app.kubernetes.io/managed-by: argocd }
subjects: [{ kind: ServiceAccount, name: order-svc }]
roleRef: { apiGroup: rbac.authorization.k8s.io, kind: Role, name: order-svc }
