apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-sandbox
resources:
- ../../base/namespaces.yaml
- ../../base/podsecurity.yaml
- ../../base/networkpolicy-default-deny.yaml
- ../../base/limitrange.yaml
- ../../base/resourcequota.yaml
- sample-app.yaml
