apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-store-csi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
    chart: secrets-store-csi-driver
    targetRevision: 1.4.6
    helm: { releaseName: csi-secrets-store }
  destination:
    server: https://kubernetes.default.svc
    namespace: ops-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-provider-aws
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://aws.github.io/secrets-store-csi-driver-provider-aws
    chart: secrets-store-csi-driver-provider-aws
    targetRevision: 0.3.9
    helm: { releaseName: csi-provider-aws }
  destination:
    server: https://kubernetes.default.svc
    namespace: ops-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
