apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-dev
  namespace: dev-sandbox
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"
    pods: "30"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-stg-exchange
  namespace: stg-exchange
spec:
  hard:
    requests.cpu: "8"
    requests.memory: "16Gi"
    limits.cpu: "16"
    limits.memory: "32Gi"
    pods: "80"
