apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources: []
helmCharts:
- name: loki-stack
  repo: https://grafana.github.io/helm-charts
  version: 2.10.2
  releaseName: loki
  namespace: observability
  valuesFile: values.yaml
