apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: signer
  namespace: prod-wallet
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: signer
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
