apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-wallet
resources:
- ../../base/namespaces.yaml
- ../../base/podsecurity.yaml
- ../../base/networkpolicy-default-deny.yaml
- ../../base/limitrange.yaml
- ../../base/resourcequota.yaml
- ../../ops-system/secrets-store-csi/kustomization.yaml
- softhsm/init-job.yaml
# signer 리소스는 services 디렉토리의 매니페스트를 사용한다고 가정
- ../../../../services/signer-rust/k8s/deployment.yaml
- ../../../../services/signer-rust/k8s/service.yaml
- ../../../../services/signer-rust/k8s/servicemonitor.yaml
- ../../../../services/signer-rust/k8s/hpa.yaml
- ../../../../services/signer-rust/k8s/pdb.yaml
- ../../../../services/signer-rust/k8s/rbac.yaml
- ../../../../services/signer-rust/k8s/netpol-egress.yaml
# 추가 netpol
- netpol.yaml
patches:
- target:
    kind: Deployment
    name: signer
  path: patches-signer-labels.yaml
- target:
    kind: Service
    name: signer
  path: patches-signer-labels.yaml
- target:
    kind: HorizontalPodAutoscaler
    name: signer
  path: patches-signer-labels.yaml
- target:
    kind: PodDisruptionBudget
    name: signer
  path: patches-signer-labels.yaml
- target:
    kind: NetworkPolicy
    name: signer-egress
  path: patches-signer-labels.yaml
- target:
    kind: Role
    name: signer
  path: patches-signer-labels.yaml
- target:
    kind: RoleBinding
    name: signer
  path: patches-signer-labels.yaml
