apiVersion: apps/v1
kind: Deployment
metadata:
  name: signer
  namespace: prod-wallet
  labels:
    app.kubernetes.io/managed-by: argocd
---
apiVersion: v1
kind: Service
metadata:
  name: signer
  namespace: prod-wallet
  labels:
    app.kubernetes.io/managed-by: argocd
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: signer
  namespace: prod-wallet
  labels:
    app.kubernetes.io/managed-by: argocd
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: signer
  namespace: prod-wallet
  labels:
    app.kubernetes.io/managed-by: argocd
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: signer-egress
  namespace: prod-wallet
  labels:
    app.kubernetes.io/managed-by: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: signer
  namespace: prod-wallet
  labels:
    app.kubernetes.io/managed-by: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: signer
  namespace: prod-wallet
  labels:
    app.kubernetes.io/managed-by: argocd
