apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: signer
  namespace: prod-wallet
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: signer
