apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
data:
  otel-config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
          grpc:
    processors:
      batch: {}
    exporters:
      prometheus:
        endpoint: "0.0.0.0:9464"
      otlp:
        endpoint: "tempo-observability:4317"
        tls:
          insecure: true
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels: {app: otel-collector}
  template:
    metadata:
      labels: {app: otel-collector}
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector:0.103.1
        args: ["--config=/conf/otel-config.yaml"]
        ports:
        - name: otlp
          containerPort: 4317
        - name: otlp-http
          containerPort: 4318
        - name: prom
          containerPort: 9464
        volumeMounts:
        - name: conf
          mountPath: /conf
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities: {drop: ["ALL"]}
      volumes:
      - name: conf
        configMap:
          name: otel-collector-config
          items:
          - key: otel-config.yaml
            path: otel-config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: observability
spec:
  selector: {app: otel-collector}
  ports:
  - name: otlp
    port: 4317
    targetPort: otlp
  - name: otlp-http
    port: 4318
    targetPort: otlp-http
  - name: prom
    port: 9464
    targetPort: prom
