apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: signer-egress
  namespace: prod-wallet
spec:
  podSelector:
    matchLabels: {app: signer}
  policyTypes: ["Egress"]
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: prod-infra
      podSelector:
        matchLabels:
          kubernetes.io/name: onprem-btc
    ports:
    - port: 8332
      protocol: TCP
