apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ops-system
resources:
- ../policies/../.. # 무시 가능(placeholder)
- ../policies/gatekeeper-constraints.yaml
- ../policies/kyverno-restrict-capabilities.yaml
- ../policies/cosign-required-constraint.yaml
- ../policies/registry-allowlist.yaml
- argocd/namespace.yaml
helmCharts:
- name: keda
  repo: https://kedacore.github.io/charts
  version: 2.14.2
  releaseName: keda
  namespace: ops-system
- name: argo-rollouts
  repo: https://argoproj.github.io/argo-helm
  version: 2.38.3
  releaseName: argo-rollouts
  namespace: ops-system
- name: secrets-store-csi-driver
  repo: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
  version: 1.4.6
  releaseName: csi-secrets-store
  namespace: ops-system
- name: secrets-store-csi-driver-provider-aws
  repo: https://aws.github.io/secrets-store-csi-driver-provider-aws
  version: 0.3.9
  releaseName: csi-provider-aws
  namespace: ops-system
resources:
- karpenter/provisioner.yaml
