apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ops-system
resources:
- ../policies/gatekeeper-constraints.yaml
- ../policies/kyverno-restrict-capabilities.yaml
- ../policies/cosign-required-constraint.yaml
- ../policies/registry-allowlist.yaml
- ../policies/gatekeeper-prod-managed-by-argocd.yaml
- argocd/namespace.yaml
- argocd/apps/
- karpenter/provisioner.yaml
- istio/kustomization.yaml
