apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: exchange-gw
  namespace: prod-exchange
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: exchange-gw
  minReplicas: 3
  maxReplicas: 60
  metrics:
  - type: Resource
    resource:
      name: cpu
      target: { type: Utilization, averageUtilization: 60 }
