apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-exchange
resources:
- ../../base/namespaces.yaml
- ../../base/podsecurity.yaml
- ../../base/networkpolicy-default-deny.yaml
- ../../base/limitrange.yaml
- ../../base/resourcequota.yaml
- ../../observability/kube-prometheus-stack/kustomization.yaml
- ../../observability/loki-stack/kustomization.yaml
- ../../observability/tempo/kustomization.yaml
- ../../observability/otel-collector.yaml
- ../../observability/blackbox/kustomization.yaml
- ../../ops-system/keda/kustomization.yaml
- ../../ops-system/karpenter/provisioner.yaml
- ../../ops-system/argo-rollouts/kustomization.yaml
- ../../ops-system/secrets-store-csi/kustomization.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- pdb.yaml
- rbac.yaml
- netpol.yaml
# Rollouts 사용 시:
# - ../exchange/rollout.yaml 로 대체
